"""Overwrite web/src/data.ts from out/<type>.json. The eval owns the numbers.

    python scripts/make_web_data.py

Types with no out/<type>.json are listed as pending, not faked.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
from mimii.const import FAR_TARGET, SR, TYPES  # noqa: E402

OUT = ROOT / "out"
DATA_TS = ROOT / "web" / "src" / "data.ts"


def _split(d: dict) -> str:
    return (f"{{ aucRoc: {d['auc_roc']:.3f}, prAuc: {d['pr_auc']:.3f}, "
            f"tprAtFar: {d['tpr_at_far']:.3f}, nPos: {d['n_pos']}, nNeg: {d['n_neg']} }}")


def main() -> int:
    results, pending = [], []
    for t in TYPES:
        p = OUT / f"{t}.json"
        if not p.exists():
            pending.append(t)
            continue
        m = json.loads(p.read_text())
        v0_p = OUT / f"{t}_v0.json"  # the raw IsolationForest + mean/std baseline
        base_ts = (
            f"\n    baseline: {_split(json.loads(v0_p.read_text())['loio'])},"
            if v0_p.exists() else "\n    baseline: null,"
        )
        results.append(
            f"  {{ type: '{t}', snrDb: {m['snr_db']}, trainIds: {json.dumps(m['train_ids'])}, "
            f"testId: '{m['test_id']}', debugId: '{m['same_id']['debug_id']}',\n"
            f"    loio: {_split(m['loio'])},\n"
            f"    sameId: {_split(m['same_id'])},{base_ts} }},"
        )
    measured = "true" if not pending else "false"
    pend_ts = json.dumps(pending)

    ts = f"""// GENERATED by scripts/make_web_data.py from out/<type>.json. Do not hand-edit;
// re-run the eval and regenerate. Numbers are measured, not illustrative.

export const MEASURED = {measured} // every listed type is a real MIMII run

export const PROTOCOL = {{
  sr: {SR},
  channel: 0,
  snrDb: 0,
  farTarget: {FAR_TARGET},
  publicIds: ['00', '02', '04', '06'] as const,
}}

export const DATASET = {{
  record: '10.5281/zenodo.3384388',
  cite: 'Purohit et al., DCASE 2019',
  types: {json.dumps(list(TYPES))} as const,
  sr: {SR},
  bitDepth: 16,
  channels: 8,
}}

export type SplitMetrics = {{
  aucRoc: number
  prAuc: number
  tprAtFar: number
  nPos: number
  nNeg: number
}}

export type TypeResult = {{
  type: string
  snrDb: number
  trainIds: string[]
  testId: string
  debugId: string
  loio: SplitMetrics       // the shipped pipeline, leave-one-model-ID-out
  sameId: SplitMetrics     // same-ID debug split
  // The raw first-cut baseline (IsolationForest on mean/std log-mel), same loio
  // split, kept so the page can show the before/after. null if not recorded.
  baseline: SplitMetrics | null
}}

// One entry per measured machine type. loio = leave-one-model-ID-out (the
// headline); baseline = the raw first-cut on the same split.
export const RESULTS: TypeResult[] = [
{chr(10).join(results)}
]

export const BASELINE = {{
  raw: 'IsolationForest on mean+std log-mel (128-d) -- the first cut, no shift handling',
  features: 'log-mel (64 bands): mean, std, p95, flux over time -> 256-d per clip',
  detector: 'per-machine normalization, then an ensemble of LOF and a diagonal GMM',
  audio: 'stdlib wave (16-bit PCM), scipy STFT - no torchaudio/librosa',
}}

// Types with no run yet. Same protocol, pending their download.
export const PENDING_TYPES: string[] = {pend_ts}
"""
    DATA_TS.write_text(ts, encoding="utf-8")
    print(f"wrote {DATA_TS} — {len(results)} measured, pending: {pending or 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
