// GENERATED by scripts/make_web_data.py from out/<type>.json. Do not hand-edit;
// re-run the eval and regenerate. Numbers are measured, not illustrative.

export const MEASURED = true // every listed type is a real MIMII run

export const PROTOCOL = {
  sr: 16000,
  channel: 0,
  snrDb: 0,
  farTarget: 0.1,
  publicIds: ['00', '02', '04', '06'] as const,
}

export const DATASET = {
  record: '10.5281/zenodo.3384388',
  cite: 'Purohit et al., DCASE 2019',
  types: ["fan", "pump", "slider", "valve"] as const,
  sr: 16000,
  bitDepth: 16,
  channels: 8,
}

export type SplitMetrics = {
  aucRoc: number
  prAuc: number
  tprAtFar: number
  nPos: number
  nNeg: number
}

export type TypeResult = {
  type: string
  snrDb: number
  trainIds: string[]
  testId: string
  debugId: string
  loio: SplitMetrics       // the shipped pipeline, leave-one-model-ID-out
  sameId: SplitMetrics     // same-ID debug split
  // The raw first-cut baseline (IsolationForest on mean/std log-mel), same loio
  // split, kept so the page can show the before/after. null if not recorded.
  baseline: SplitMetrics | null
}

// One entry per measured machine type. loio = leave-one-model-ID-out (the
// headline); baseline = the raw first-cut on the same split.
export const RESULTS: TypeResult[] = [
  { type: 'fan', snrDb: 0, trainIds: ["00", "02", "04"], testId: '06', debugId: '00',
    loio: { aucRoc: 0.971, prAuc: 0.896, tprAtFar: 0.961, nPos: 361, nNeg: 1015 },
    sameId: { aucRoc: 0.675, prAuc: 0.553, tprAtFar: 0.157, nPos: 407, nNeg: 506 },
    baseline: { aucRoc: 0.467, prAuc: 0.278, tprAtFar: 0.127, nPos: 361, nNeg: 1015 }, },
  { type: 'pump', snrDb: 0, trainIds: ["00", "02", "04"], testId: '06', debugId: '00',
    loio: { aucRoc: 0.933, prAuc: 0.684, tprAtFar: 0.784, nPos: 102, nNeg: 1036 },
    sameId: { aucRoc: 0.886, prAuc: 0.798, tprAtFar: 0.839, nPos: 143, nNeg: 503 },
    baseline: { aucRoc: 0.627, prAuc: 0.164, tprAtFar: 0.353, nPos: 102, nNeg: 1036 }, },
  { type: 'slider', snrDb: 0, trainIds: ["00", "02", "04"], testId: '06', debugId: '00',
    loio: { aucRoc: 0.920, prAuc: 0.533, tprAtFar: 0.730, nPos: 89, nNeg: 534 },
    sameId: { aucRoc: 0.515, prAuc: 0.419, tprAtFar: 0.104, nPos: 356, nNeg: 534 },
    baseline: { aucRoc: 0.601, prAuc: 0.179, tprAtFar: 0.112, nPos: 89, nNeg: 534 }, },
  { type: 'valve', snrDb: 0, trainIds: ["00", "02", "04"], testId: '06', debugId: '00',
    loio: { aucRoc: 0.800, prAuc: 0.292, tprAtFar: 0.350, nPos: 120, nNeg: 992 },
    sameId: { aucRoc: 0.922, prAuc: 0.714, tprAtFar: 0.807, nPos: 119, nNeg: 496 },
    baseline: { aucRoc: 0.323, prAuc: 0.086, tprAtFar: 0.083, nPos: 120, nNeg: 992 }, },
]

export const BASELINE = {
  raw: 'IsolationForest on mean+std log-mel (128-d) -- the first cut, no shift handling',
  features: 'log-mel (64 bands): mean, std, p95, flux over time -> 256-d per clip',
  detector: 'per-machine normalization, then an ensemble of LOF and a diagonal GMM',
  audio: 'stdlib wave (16-bit PCM), scipy STFT - no torchaudio/librosa',
}

// Types with no run yet. Same protocol, pending their download.
export const PENDING_TYPES: string[] = []
